// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt71mgK8Oxpg6CJRv4tZQ1PUhCHFVF2nk',
    appId: '1:306925937148:web:14bb543b82cf79f8145279',
    messagingSenderId: '306925937148',
    projectId: 'blog-app-2fd85',
    authDomain: 'blog-app-2fd85.firebaseapp.com',
    storageBucket: 'blog-app-2fd85.appspot.com',
    measurementId: 'G-64KEBTSDG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwiMc5qa_dg-e5U5Ge3QUzv8yUqNaNUmA',
    appId: '1:306925937148:android:4b78747e3c3268e3145279',
    messagingSenderId: '306925937148',
    projectId: 'blog-app-2fd85',
    storageBucket: 'blog-app-2fd85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoKIBpZuZN6s_xE099lTTkDTYaXks9EFA',
    appId: '1:306925937148:ios:dfc47d57c3d539d9145279',
    messagingSenderId: '306925937148',
    projectId: 'blog-app-2fd85',
    storageBucket: 'blog-app-2fd85.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoKIBpZuZN6s_xE099lTTkDTYaXks9EFA',
    appId: '1:306925937148:ios:dfc47d57c3d539d9145279',
    messagingSenderId: '306925937148',
    projectId: 'blog-app-2fd85',
    storageBucket: 'blog-app-2fd85.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

}